# Generated by Django 5.0.6 on 2024-07-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NacionNoticias',
            fields=[
                ('id_Nacion_Noticias', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_Nacion_Noticias', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tipoNoticia',
            fields=[
                ('id_tipo_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo_noticia', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_noticia', models.CharField(max_length=80)),
                ('decripcion_noticia', models.CharField(max_length=255)),
                ('fecha_noticia', models.DateField()),
                ('imagen_noticia', models.ImageField(default='core/img/eventoGenerico.jpg', upload_to='core/img/')),
                ('Nacion_Noticias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.nacionnoticias', verbose_name='Nacion Noticias')),
                ('tipo_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.tiponoticia', verbose_name='Tipo Noticia')),
            ],
        ),
    ]
