# Generated by Django 5.0.6 on 2024-07-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='Nacion_Noticias',
            new_name='id_Nacion_Noticias',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='tipo_noticia',
            new_name='id_tipo_noticia',
        ),
    ]
