# Generated by Django 5.0.6 on 2024-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_nacion_noticias_noticia_id_nacion_noticias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicar_noticia',
            field=models.BooleanField(default=False),
        ),
    ]
