# Generated by Django 5.0.6 on 2024-07-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_publicar_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='decripcion_noticia',
            field=models.CharField(max_length=1000),
        ),
    ]
